version: '3'

# https://www.emqx.io/docs/zh/v5.0/deploy/install-docker.html#%E9%80%9A%E8%BF%87-docker-compose-%E6%9E%84%E5%BB%BA-emqx-%E9%9B%86%E7%BE%A4
# https://github.com/emqx/emqx/tree/master/deploy/docker
services:
  emqx1:
    image: emqx/emqx:5.0.19
    container_name: emqx1
    environment:
      - 'EMQX_NODE_NAME=emqx@node1.emqx.com'
      # - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      # - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]'
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx_ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.com
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
#    volumes:
      #- ./emqx1/data:/opt/emqx/data
      #- ./emqx1/etc:/opt/emqx/etc
      #- ./emqx1/log:/opt/emqx/log

  # emqx2:
  #   image: emqx/emqx:5.0.19
  #   container_name: emqx2
  #   environment:
  #     - 'EMQX_NODE_NAME=emqx@node2.emqx.com'
  #     - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
  #     - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]'
  #   healthcheck:
  #     test: ['CMD', '/opt/emqx/bin/emqx_ctl', 'status']
  #     interval: 5s
  #     timeout: 25s
  #     retries: 5
  #   networks:
  #     emqx-bridge:
  #       aliases:
  #         - node2.emqx.com
  #   volumes:
  #     - ./emqx2/data:/opt/emqx/data
  #     - ./emqx2/etc:/opt/emqx/etc
  #     - ./emqx2/log:/opt/emqx/log

networks:
  emqx-bridge:
    driver: bridge
